### ISSUE TITLE
[bug] Add reverse for `account_email`

### ISSUE THREAD

**Issue by codesankalp** [openwisp/openwisp-users#241]
After registering a user from the admin site in openwisp-controller and openwisp-radius and clicking on the confirm-email link it gives this error because reverse for `account_email` is not in `openwisp_users.account.urls`:
![image](https://user-images.githubusercontent.com/56037184/115535960-e08cbf00-a2b6-11eb-8836-8697072ee36e.png)

**Possible solution**: Add URL for `account_email` in `openwisp_users.account.urls` to avoid this error in all other repos.

**Comment by codesankalp** [comment]
@nemesisdesign Instead of adding `allauth.urls` in `urls.py`of `openwisp-radius` issue I thought to fix this here because this issue is in each repo where `openwisp_users.account.urls` is used in `accounts/` endpoint.
Can you please confirm this to solve this here or not so that I can make a PR to fix this?

**Comment by nemesisdesign** [comment]
@codesankalp I think you're focusing on the symptoms instead of the root cause.

First of all we must ask: is this missing URL a deliberate choice or was it forgotten?
Response: it's deliberate, because that URL is used to allow the user to change their email through some views and templates which we currently do not use.

Infact that template that in openwisp-radius fails, it's overridden in this module purposely for that reason, to remove that URL resolution: https://github.com/openwisp/openwisp-users/blob/master/openwisp_users/accounts/templates/account/email_confirm.html

Therfore the right solution is to understand why the override is not working in openwisp-radius and fix that there.

Please put effort in always digging to the root cause of every issue.

**Comment by nemesisdesign** [comment]
@codesankalp most probably the reason of the issue is just the order of the installed apps:
https://github.com/openwisp/openwisp-radius/blob/master/tests/openwisp2/settings.py#L28-L43

Take a look at the settings of openwisp-users: https://github.com/openwisp/openwisp-users/blob/master/tests/openwisp2/settings.py#L24-L30

Do you see the difference?

**Comment by codesankalp** [comment]
> @codesankalp most probably the reason of the issue is just the order of the installed apps:
> Do you see the difference?

Yes, It's related to the ordering apps.

> @codesankalp I think you're focusing on the symptoms instead of the root cause.
> Therfore the right solution is to understand why the override is not working in openwisp-radius and fix that there.
> Please put effort in always digging to the root cause of every issue.

I thought this is the cause of the error so I created it because it is occurring in the openwisp-controller as well.
But from next time I will put more effort and will ask on Gitter before creating an issue.

Closing this issue.
