### ISSUE TITLE
[admin] existing OrganizationUser in inline should always show the org related to that user

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-users#44]
**Bug**: if operator not admin in an organisation, the USER ORGANIZATIONS contains ----- instead of the name of organisation.

This problem came out while working on #38.

**Comment by atb00ker** [comment]
if an operator `is_admin` in org1 and **not** `is_admin` in org2 and a member of default, org1 and org2 exist. Since, this member's record is visible to operator. The dropdown box doesn't contain the name of other organisations it looks like
![this](https://user-images.githubusercontent.com/24985760/47264510-35102180-d536-11e8-8ac4-4679711fad12.png).

It is will always occur in case of #34 (when the operator tries to open his own change_user form).

**Comment by NoumbissiValere** [comment]
Please can i work on this?

**Comment by atb00ker** [comment]
Yes, sure, you can always work on issues that no one is working on. :smile:

**Comment by NoumbissiValere** [comment]
![screenshot from 2019-02-11 15-23-04](https://user-images.githubusercontent.com/24882630/52569249-05e92d00-2e11-11e9-81fc-844128d54d93.png)
I was working on this issue and this is what i get when i visit the user/change page. I <strong>don't</strong> experience the problem as stated here. eventhought valere is not an admin in ```org1```, i am able to see it in the change user page and am equally able to access the dropdown box as we can see in the figure. please @nemesisdesign  or @atb00ker  can you tell me if am doing it wrong so that i can do it the right way and solve the problem? thanks/.

**Comment by atb00ker** [comment]
@NoumbissiValere is your user a superuser? ( that could be enabling you to see all the orgs! ) :smile:

**Comment by NoumbissiValere** [comment]
Hmmmmmm. maybe. i will look into that @atb00ker
