### ISSUE TITLE
[admin] Creating a new user with invalid email address generates a `Server Error (500)`.

### ISSUE THREAD

**Issue by isranetworks** [openwisp/openwisp-users#72]
Adding a new user with a `fake email` will output a `Server error (500)` message. Adding the new user again with a `real email` will succeed and the system will add the new user accordingly. From this point, the new user can now be edited with a `fake email` and the `real email` can now be removed from the database. 

Please see mailing list topic: [Fresh installation of Debian 9 server + ansible-openwisp2, gateway error 500](https://groups.google.com/d/topic/openwisp/GGdRDusLPgI/discussion)

Thank you

**Comment by MiHiR151203** [comment]
Invalid Email Address ?

But I Used A Valid One !

**Comment by nemesisdesign** [comment]
It may be related or the cause of https://github.com/openwisp/ansible-openwisp2/issues/132

**Comment by NoumbissiValere** [comment]
I can't replicate this issue on my local development `openwisp_users` repo. I am still able to create users with fake emails in my local `openwisp_users` repo. Please can someone help me to replicate the issue on my local `openwisp_users` repo so that i might be able to provide a fix? Thanks

**Comment by nemesisdesign** [comment]
@NoumbissiValere by default, the test project runs the console email backend and prints emails to the standard output of the development server.

In order to test it, you should set it to the default email backend of django and then continue tweaking and testing from there.

**Comment by NoumbissiValere** [comment]
@nemesisdesign 
1) I replaced the console backend with the default backend as you suggested . this is the backend i put : ```EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'```  (even though django uses this by default)
But i was still able to create users with an invalid email such as `tests@gmail.com`
2) I equally tried turning off debugging thinking it was the problem but i didn't still replicate the issue
3) i equally added the following settings but it didn't still work
```
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'my_real_email'
EMAIL_HOST_PASSWORD = my_real_email_password'
```
all i get is an email from `example.com` saying address not found. but the user was still created.

Please what am i doing wrong. I will love to be corrected.

**Comment by nemesisdesign** [comment]
you should not configure the real SMTP, because of course in that case it won't fail but it will work.
This error happens when the default settings are used, a local postfix instance is running and for some reason postfix returns error when sending the email

**Comment by NoumbissiValere** [comment]
@nemesisdesign on my vagrant VM, i was not able to even add a user whether with valid email or not (was getting the server 500 error). when i check the openwisp2 error log, i got this error message.
`File "/usr/lib/python3.5/smtplib.py", line 862, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (501, b'5.1.7 Bad sender address syntax', 'openwisp2@192.168.56.5')
`
I thought that postfix is trying to use `openwisp2@192.168.56.5` as sender email which doesn't exists and thus the `SMTPSenderRefused` exception. So i opened the `settings.py` of openwisp2 and changed the `DEFAULT_FROM_EMAIL` to an email which exists and i was able to create users with valid and invalid emails. 
I am thinking that the problem is not in the code but either in the settings or the way the postfix is configured

**Comment by nemesisdesign** [comment]
@NoumbissiValere I think this is good enough to write a fix.

The system should not fail with 500 internal server error. I suggest to proceed this way:

- write a test that mocks the part of the code which triggers the sending of the email so that the mocked method raises an exception, for example, `smtplib.SMTPSenderRefused`
- ensure the test fails
- wrap the code that sends the email in a try/except block which catches `Exception` and uses `logger.exception('Error while sending email verification to user')` to log the exception

This will avoid the 500 internal server error that many of our users are having. Emails won't be sent, but advanced users will find out by inspecting the logs or they will get error exceptions via sentry.io. Beginner users won't even notice because they may not even need this feature or be aware this exists, so in the future we may need to make this more explicit in the docs, but at least now we will not prevent users from adding new users into their openwisp instance.

**Comment by NoumbissiValere** [comment]
I think it is a great idea. 
i have a problem: Please how will I test the fix on my Vagrant Box. The openwisp2 is running on the VM which was created by vagrant. How do i get the modified `openwisp_users` to this openwisp2 instance to test it ?
Thanks

**Comment by nemesisdesign** [comment]
@NoumbissiValere

try this:
```bash
cd /opt/openwisp2
source env/bin/activate  # activate python virtualenv
pip install --upgrade https://github.com/NoumbissiValere/openwisp-users/tarball/<your-branch-here>
# look into /opt/openwisp2/env to find the code of openwisp-users and ensure your changes are there
# you can find out the exact path location by opening the python shell and checking openwisp_users, eg:
# python
# >>> import openwisp_users
# >>> openwisp_users
# will tell you where the openwisp_users package is located on the filesystem.
# once you are sure the code has been upgraded you have to restart openwisp with:
supervisorctl restart all
```
